### ISSUE TITLE
Data-loading issue: Couldn't find any class folder in /raw_data/validation

### ISSUE THREAD

**Issue by gcunhase** [clevercool/SQuant#3]
Can you please include the steps to download the dataset?
I downloaded the dataset from the official website and my directory contains `train` and `validation` directories with `.JPEG` images. However, I'm facing the following error when I try running this code:
```
main.py --model resnet18 --mode squant -wb 4 -ab 4 -s 12
06/13/2022 14:39:23 - INFO - __main__ -   squant_log/resnet18_imagenet/squant_W4A4_27616
06/13/2022 14:39:23 - INFO - __main__ -   Namespace(abit=4, batch_size=256, constraint_radius=1.0, dataset='imagenet', dataset_path='/media/Data/imagenet_data', disable_activation_quant=False, disable_quant=False, mode='squant', model='resnet18', packed_element=1, percent=100, sigma=12.0, wbit=4)
06/13/2022 14:39:23 - INFO - __main__ -   ==> Building model..
06/13/2022 14:39:26 - INFO - __main__ -   ==> Setting quantizer..
06/13/2022 14:39:27 - INFO - __main__ -   SQuant Start!
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.0.conv.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 3.105477 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.1.0.body.conv1.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.1.0.body.conv1.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.599318 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.1.0.body.conv2.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.1.0.body.conv2.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.383950 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.1.1.body.conv1.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.1.1.body.conv1.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.356500 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.1.1.body.conv2.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.1.1.body.conv2.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.415688 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.0.identity_conv.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.0.identity_conv.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.209613 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.0.body.conv1.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.0.body.conv1.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.561075 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.0.body.conv2.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.0.body.conv2.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.882723 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.1.body.conv1.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.1.body.conv1.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.524123 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.1.body.conv2.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.2.1.body.conv2.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.696750 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.0.identity_conv.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.0.identity_conv.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.275405 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.0.body.conv1.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.0.body.conv1.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.787184 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.0.body.conv2.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.0.body.conv2.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 2.378979 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.1.body.conv1.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.1.body.conv1.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 2.330407 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.1.body.conv2.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.3.1.body.conv2.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 2.377668 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.0.identity_conv.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.0.identity_conv.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.564287 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.0.body.conv1.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.0.body.conv1.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 3.622235 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.0.body.conv2.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.0.body.conv2.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 6.244142 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.1.body.conv1.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.1.body.conv1.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 6.248601 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.1.body.conv2.conv.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: features.4.1.body.conv2.conv.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 6.254070 ms
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 8 bit: output.quant_input 
06/13/2022 14:39:27 - INFO - quant_modules -   QUANT 4 bit: output.quant_weight 
06/13/2022 14:39:27 - INFO - quant_modules -   Quantzation time: 1.655975 ms
06/13/2022 14:39:27 - INFO - __main__ -   SQuant has Done!
06/13/2022 14:39:27 - INFO - __main__ -   ==> Preparing data..
Traceback (most recent call last):
  File "/home/nvidia/PycharmProjects/SQuant/main.py", line 145, in <module>
    testloader = getTestData(args.dataset,
  File "/home/nvidia/PycharmProjects/SQuant/dataloader.py", line 43, in getTestData
    test_dataset = datasets.ImageFolder(
  File "/home/nvidia/PycharmProjects/SQuant/venv28/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 310, in __init__
    super().__init__(
  File "/home/nvidia/PycharmProjects/SQuant/venv28/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/nvidia/PycharmProjects/SQuant/venv28/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 219, in find_classes
    return find_classes(directory)
  File "/home/nvidia/PycharmProjects/SQuant/venv28/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 43, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in /media/Data/imagenet_data/validation.

Process finished with exit code 1
```

**Comment by clevercool** [comment]
Thanks for your attention to our work.
You can refer to the official [example](https://github.com/pytorch/examples/tree/main/imagenet) and this [script](https://github.com/pytorch/examples/blob/main/imagenet/extract_ILSVRC.sh) to organize your ImageNet dataset.

**Comment by clevercool** [comment]
OK, thanks for your advice.

**Comment by gcunhase** [comment]
Thank you!
