### ISSUE TITLE
AssertionError with res50 (8 bit-width) and inceptionv3 (all bit-width)

### ISSUE THREAD

**Issue by piaopu0120** [clevercool/SQuant#9]
Dear SQuant team,

I am a college student of computer science. I found your paper accepted by ICLR2022 named SQuant: On-the-fly Data-free Quantization Via Diagonal Hessian Approximation. I am deeply impressed by the speedup and high accuracy of the quantized models. And I clone the git repo to try it myself. It runs successfully on most architectures and the results are just the same as reported. However, it encounters an AssertionError when I run the command in `run.sh` under setting `--model resnet50 --mode squant -wb 8 -ab 8 -s 25` and `--model inceptionv3` with all bit-width settings. I am curious that if there are any missing arguments. It would be very thankful if you could give some instructions. 

Best regards.

**Comment by clevercool** [comment]
Hi, thanks for your attention.
Could you provide the details about the error?

**Comment by piaopu0120** [comment]
> 

For instance, it occurs the following error when quantizing inceptionv3 `features.0.conv5.conv.quant_weight `:



```
Traceback (most recent call last):
  File "main.py", line 155, in <module>
    quantized_model(rand_input)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/pytorchcv/models/inceptionv3.py", line 602, in forward
    x = self.features(x)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/pytorchcv/models/inceptionv3.py", line 516, in forward
    x = self.conv5(x)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/pytorchcv/models/inceptionv3.py", line 53, in forward
    x = self.conv(x)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk2/dyf/codes/squant/SQuant-dsg/quant_modules.py", line 375, in forward
    weight = self.quant_weight(self.weight)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk2/dyf/codes/squant/SQuant-dsg/quant_modules.py", line 302, in forward
    return self.tensor_forward(tensor, image_size)
  File "/disk2/dyf/codes/squant/SQuant-dsg/quant_modules.py", line 291, in tensor_forward
    self._init_quant_para(tensor)
  File "/home/dell/miniconda3/envs/squant/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/disk2/dyf/codes/squant/SQuant-dsg/quant_modules.py", line 258, in _init_quant_para
    self.quant_weight_tensor = _quant(data)
  File "/disk2/dyf/codes/squant/SQuant-dsg/quant_modules.py", line 247, in _quant
    quant_tensor = self.adaptive_round(quant_tensor, -n, n - 1)
  File "/disk2/dyf/codes/squant/SQuant-dsg/quant_modules.py", line 194, in adaptive_round
    assert (rounding_number.unique().numel() <= 2 ** self.bit.item())
AssertionError
```

**Comment by clevercool** [comment]
Thanks for reporting this bug.
I have fixed it. It won't impact the accuracy.

**Comment by piaopu0120** [comment]
Thx for your immediate reply. It perfectly solved my problem.
